name: Test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'


jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: hey
        run: echo "hey you"
      
